// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab7PPTPM.Data;

#nullable disable

namespace lab7PPTPM.Migrations
{
    [DbContext(typeof(lab7PPTPMContext))]
    partial class lab7PPTPMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("lab7PPTPM.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeePassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeePatronymic")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("lab7PPTPM.Model.PositionJob", b =>
                {
                    b.Property<int>("PositionJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PositionJobId");

                    b.ToTable("PositionJob");
                });
#pragma warning restore 612, 618
        }
    }
}
